services:
  homeassistant:
    container_name: ${SERVICE_NAME}
    image: homeassistant/home-assistant:latest
    depends_on:
      - mariadb
    #      - influxdb
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    #    devices:
    #      - /dev/ttyACM0
    environment:
      - PUID=1000
      - PGID=100
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - smarthome
      - proxy
      - external
    labels:
      - homepage.name=Home Assistant
      - homepage.description=Home automation platform
      - homepage.icon=home-assistant
      - homepage.href=https://${SERVICE_NAME}.${MY_DOMAIN}
      - homepage.group=Dev & Automation
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=http
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${MY_DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}.middlewares=default-whitelist@file
      - traefik.http.middlewares.${SERVICE_NAME}-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-https-redirect
      - traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=https
      - traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${SERVICE_NAME}.${MY_DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}-secure.tls=true
      - traefik.http.routers.${SERVICE_NAME}-secure.service=${SERVICE_NAME}
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_INTERNAL_PORT}
      - traefik.docker.network=proxy

  # influxdb:
  #    container_name: homeassistant_history
  #    image: influxdb:latest
  #    restart: unless-stopped
  #    ports:
  #      - "8086:8086"
  #      - "8083:8083"
  #    volumes:
  #      - ./influxdb:/var/lib/influxdb
  #      - /etc/localtime:/etc/localtime:ro
  #    environment:
  #      INFLUXDB_DB: homeassistant
  #      INFLUXDB_USER: homeassistant
  #      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
  #    networks:
  #      - default

  mariadb:
    container_name: homeassistant_recorder
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_USER=homeassistant
      - MYSQL_DATABASE=homeassistant
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
#  adminer:
#    container_name: homeassistant_recorder_mgmt
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 8280:8080
#    networks:
#      - default

networks:
  smarthome:
    external: true
  proxy:
    external: true
  external:
    external: true
