services:

  homeassistant:
    container_name: ${SERVICE_NAME}
    image: homeassistant/home-assistant:latest
    depends_on:
      - mariadb
#      - influxdb
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - ./config:/config
#      - ${CERT_PATH}:/config/certs
      - /etc/localtime:/etc/localtime:ro
#    devices:
#      - /dev/ttyACM0
    environment:
      - PUID=1000
      - PGID=100
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=http"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${MY_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.${SERVICE_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-https-redirect"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${SERVICE_NAME}.${MY_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.service=${SERVICE_NAME}"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_INTERNAL_PORT}"
      - "traefik.docker.network=proxy"

#  influxdb:
#    container_name: homeassistant_history
#    image: influxdb:latest
#    restart: unless-stopped
#    ports:
#      - "8086:8086"
#      - "8083:8083"
#    volumes:
#      - ./infuxdb:/var/lib/influxdb
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      INFLUXDB_DB: homeassistant
#      INFLUXDB_USER: homeassistant
#      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
#    networks:
#      proxy:

  mariadb:
    container_name: homeassistant_recorder
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=homeassistant
      - MYSQL_DATABASE=homeassistant
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb/db:/var/lib/mysql
#      - ./mariadb/my.cnf:/etc/mysql/my.cnf:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      proxy:

#  adminer:
#    container_name: homeassistant_recorder_mgmt
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 8280:8080
#    networks:
#      proxy:

#  nodered:
#    container_name: nodered
#    image: nodered/node-red
#    restart: unless-stopped
#    ports:
#      - 1880:1880
#    volumes:
#      - ./nodered:/data
#    depends_on:
#      - homeassistant
#      - mosquitto

#  mosquitto:
#    container_name: mosquitto
#    image: eclipse-mosquitto
#    restart: unless-stopped
#    ports:
#      - 1883:1883
#    volumes:
#      - ./mosquitto/config:/mosquitto/config
#      - ./mosquitto/data:/mosquitto/data
#      - ./mosquitto/log:/mosquitto/log
#      - /etc/localtime:/etc/localtime:ro

networks:
  proxy:
    external: true
